dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_esignet:
    enabled: true
    host: "esignet-postgresql.<sandbox>.mosip.net"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    branch: v1.5.0
