dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_esignet_mock:
    enabled: true
    host: "postgres.esdevtest.mosip.net"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    branch: develop-go
