modules:
  esignet:
    enabled: true
    image:
      repository: mosipid/apitest-esignet
      tag: 1.5.0
      pullPolicy: Always

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi
